app:
  version: ${APP_VERSION:0.0.2}


spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:32770}/${DB_NAME:devdb}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:devpassword}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
kafka:
  bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER_HOST:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:9092}
  producer:
  consumer:
    group-id: mygroup
    auto-offset-reset: earliest




springdoc:
  swagger-ui:
    path: /apidocs
