app:
  version: ${APP_VERSION:-0.0.1}


spring:
  datasource:
    url: ${DB_URL:-jdbc:postgresql://localhost:32770/devdb}
    username: ${DB_USERNAME:-dev}
    password: ${DB_PASSWORD:-devpassword}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml



springdoc:
  swagger-ui:
    path: /apidocs
