apiVersion: v1
kind: Service
metadata:
  name: awsservices-linux-service
  namespace: awsservices-app
  labels:
    app: awsservices-linux-app
spec:
  type: LoadBalancer
  selector:
    app: awsservices-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080